class_name Service extends RefCounted

enum Type {
	CHARACTER_MANAGER,
	CITY_MANAGER,
	CONFIG_MANAGER,
	COUNTRY_MANAGER,
	DIALOG_MANAGER,
	MOD_MANAGER,
	SCENE_MANAGER,
	SESSION_MANAGER,
	TRADE_MANAGER,
	WORLD_MANAGER,
}
